### ISSUE TITLE
JSON array convert to object in MI

### ISSUE THREAD

**Issue by veneerac** [wso2/product-micro-integrator#3602]
### Description

When using the above XPath, the JSON is converted to a JSONObject, and upon changing the message type back to JSON, single-element arrays are converted into objects.JSON object

### Steps to Reproduce

Use ForEach mediator with a Filter mediator to loop through a JSON, as described below.

```
<foreach expression="//profiles[1]/attachments" id="Itr1">
    <sequence>
        <filter xpath="//attachments/type='PHOTO'">
            <then>
                <property description="Read Photo" expression="//attachments/base64" name="Photo_value" scope="default" type="STRING"/>
                <property name="messageType" scope="axis2" value="application/json"/>
            </then>
            <else>
                            
                        </else>
        </filter>
    </sequence>
</foreach>
```

### Affected Version(s)

MI 4.2.0.86

**Comment by malakaganga** [comment]
Already fixed in master this issue is to add a property to restore previous behaviour
