### ISSUE TITLE
wso2update*.* are missing in the version 4.3.0

### ISSUE THREAD

**Issue by WaelfatoEib** [wso2/product-micro-integrator#3776]
### Description

Following your documentation to setup a new version of wso2mi, a step to update the product is required.
While trying to upgrade to v4.3.0, we noticed that the scripts 'wso2update*.*' are missing in the binaries of the new version "4.3.0"

### Steps to Reproduce

- Download wso2mi v.4.3.0 from the url: https://wso2.com/micro-integrator/?download=true
- unzip the downloaded binaries
- navigate to ./wso2mi-4.3.0/bin

you would see no 'wso2update*.*' scripts

### Version

4.3.0

### Environment Details (with versions)

OS: all

**Comment by rosensilva** [comment]
@WaelfatoEib , 
You need to have a subscription to get downloads according to the following doc,
https://updates.docs.wso2.com/en/latest/updates/overview/#how-do-you-get-wso2-updates

**Comment by anupama-pathirage** [comment]
Closing this issue as per the above comment. @WaelfatoEib Please feel free to reopen the issue if you have further queries.
